server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&useSSL=true
    username: root
    password: bigjoey86
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  # REDIS (RedisProperties)
  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    #Redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 0
    jedis:
      # 连接池最大连接数（使用负值表示没有限制）
      pool.max-idle: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      pool.max-wait: -1
      ## 连接池中的最大空闲连接
      #spring.redis.jedis.pool.max-idle=8
      # 连接池中的最小空闲连接
      pool.min-idle: 0

  ## RABBIT (RabbitProperties)
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: guest
    application.name: spirng-boot-rabbitmq

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapperLocations: classpath:mapper/*.xml  #指定*Mapper.xml的位置
  type-aliases-package: com.demo.entity

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9090/eureka/


#设置日志级别，打印mybatis的日志
#logging:
#  level:
#    root: debug